### ISSUE TITLE
training result

### ISSUE THREAD

**Issue by hanish3464** [parksunwoo/ocr_kor#6]
naver deep text recognition issue에 타고 들어오다가 질문 남깁니다!

한국어 data 까지 생성하신 것 같은데 트레이닝 결과는 잘 나오나요?

현재 어떤 이슈가 있는지 혹시 한계점으로 보신게 어떤것이 있는지 알고 싶습니다!

감사합니다.

**Comment by parksunwoo** [comment]
안녕하세요~ 기존 영문에서 사용하던 파라미터를 그대로 사용했을때 최대성능은 29%정도였는데
파라미터를 조금씩 조정하면서 현재는 84-85% 정도까지는 성능이 나오는것 같습니다

추가적인 성능 개선을 위해서 몇가지 고려중인건 아래정도입니다
- 데이터자체를 단어의 조합에서 실제 임의 문장으로 
- 모델조합에 kor-bert 추가

시간되는대로 모델파일도 업로드할 생각입니다~

**Comment by hanish3464** [comment]
관련 프로젝트 때문에 한번 test를 해보고 싶습니다!
85퍼센트의 성능이라는게 어느정도인지 잘 와닿지가 않네요 ㅠㅠ
혹시 85퍼센트라고 하시면 100개의 글자가 있으면 모델이 평균적으로 85개의 글자를 정확하게
예측한다는 것이 맞나요??
혹시 직접적인 결과를 확인할 수 있는 방법이 있을까요!?
감사합니다!!

**Comment by parksunwoo** [comment]
예측된 문장과 실제 문장을 비교해서 정확도를 측정하고 있습니다. 질문하신 대로라면 100개의 문장중에 85개 문장을 정확히 예측한다는 게 되겠네요.
정확도가 가장 높았던 모델(TPS-VGG-BiLSTM-Attn)의 로그정보와 모델 다운로드 링크 추가했습니다. 한번 보시고 궁금하신건 또 글남겨주세요~ 
[log_train.txt](https://github.com/parksunwoo/ocr_kor/blob/master/exprement2/TPS-VGG-BiLSTM-Attn-Seed9998/log_train.txt)
[download models](https://github.com/parksunwoo/ocr_kor#download-models-best-accuracy)

**Comment by hanish3464** [comment]
감사합니다! 
한번 테스트 진행해보려고 하는데 에러를 만났는데 혹시 이유를 알 수 있을까요?
![image](https://user-images.githubusercontent.com/51018265/66727471-5de1a300-ee7a-11e9-85b1-ea8c04465d0d.png)
(demo.py 에서도 한번 돌려봤는데 잘안되더라구요)
우선 repo에는 없는 폴더가 test 가이드에는 들어있어서 어떻게 하면 좋을지 여쭤보고 싶네요!

어느정도 난이도에서 인식이 가능한지 알고 싶어서 그러는데 test  로 이용하신 이미지가 혹시 어떤 것이었는지 알려주시면 정말 감사하겠습니다!

감사합니다!

**Comment by parksunwoo** [comment]
우선 제가 진행하는 프로젝트에 관심가져주셔서 감사합니다. demo도 다시한번 돌려보게 되었네요. 제 기억으론 위 에러는 환경설정이 맞지않을때 나왔던걸로 기억합니다. 방금 모델수행해본 제 가상환경은 (pytorch 1.2.0, Python 3.6.5) 이네요.

데모 수행 스크립트를 추가했습니다. 참고하셔서 다운로드 받은 모델파일과 이미지파일 경로를 잡아주시면 될 것 같습니다.
https://github.com/parksunwoo/ocr_kor#demo

repo에 없는 폴더라는게 data/data_lmdb_release/evaluation 부분을 말씀하시는거라면
https://github.com/parksunwoo/ocr_kor#create-lmdb-dataset 부분에서 training 데이터를 생성한것처럼 validation, evaluation 데이터를 생성해서 진행했습니다. 

테스트한 이미지는 깃허브에 올려둔 이미지와 형태는 비슷합니다, 제가 생성한 데이터는 10개단어길이 정도로 했었습니다.

- 이미지 경로
https://github.com/parksunwoo/ocr_kor/blob/master/data/generator/TextRecognitionDataGenerator/out/

위 경로에 있는 데이터 중에 몇개를 확인해보니 결과값은 아래와 같이 나옵니다. 잘나오는 것 기준으로 올렸는데 아예 다른게 나오는 케이스들도 있네요^^;

basic/중반 용서하다 치우다 깊숙이 화요일 그만큼 가요 쪽 혹시 자라나다_0.jpg        
**중반용서하다치우다깊숙이화요일그만큼가요쪽혹시자라나 다**
basic/지도 씨름 나이 눈썹 결혼 조깅 궁금하다 대중 뚜껑 충돌_1.jpg  
**지도씨름나이눈썹결혼조깅궁금하다대중뚜껑충돌**

궁금한건 언제든 글 남겨주세요~

**Comment by hanish3464** [comment]
말씀해주신건 잘 확인했습니다 감사합니다!
데모를 실행할 수 있어서 좋네요 ㅎㅎ 그런데..
![image](https://user-images.githubusercontent.com/51018265/66977750-19f0d700-f0e2-11e9-82a6-54bb0a993475.png)
demo.py 를 실행하면 다음과 같은 에러를 만나네요..   pytorch 1.2.0 에 python 3.7.3 인데 파이썬 버전을 다운그레이드 해야하나요!?

감사합니다!

**Comment by parksunwoo** [comment]
https://github.com/parksunwoo/ocr_kor/blob/master/deep-text-recognition-benchmark/modules/transformation.py#L152

152 라인 코드로 한번 해보시겠어요?

**Comment by hongym7** [comment]
@parksunwoo 자료 감사합니다.
152 라인 코드로 하면 아래와 같이 오류가 납니다

Traceback (most recent call last):
  File "/home/hong/PycharmProjects/ocr_kor/deep-text-recognition-benchmark/demo_org.py", line 134, in <module>
    demo(opt)
  File "/home/hong/PycharmProjects/ocr_kor/deep-text-recognition-benchmark/demo_org.py", line 70, in demo
    preds = model(image, text_for_pred, is_train=False)
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/hong/venv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'input' and 'text'


Process finished with exit code 1

**Comment by parksunwoo** [comment]
남겨주신 로그만으로는 정확히 어떤 문제인지 확인이 힘든데요.

`preds = model(image, text_for_pred, is_train=False) `

TypeError: forward() missing 2 required positional arguments: 'input' and 'text'

해당부분을 중점적으로 디버깅 해보시면 답을 찾으실수 있을듯합니다

한번해보시고 알려주세요

**Comment by hongym7** [comment]
@parksunwoo 
네, 혹시 사용하셨던 것들 버젼 알 수 있을까요?
위에 내용 보니 (pytorch 1.2.0, Python 3.6.5) 이시네요

python
pytorch
cuda
ubuntu

해당 버젼 맞추고 해야 할 것 같아서요
감사합니다 ^^

**Comment by NeighborhoodCoding** [comment]
Demo.py는 powershell에서 실행하면 안되는건가요? 아무런 사진이 안뜨고 도스창에서 
```
model input parameters 32 400 20 1 512 256 974 50 TPS VGG BiLSTM Attn
loading pretrained model from deep-text-recognition-benchmark/saved_models/TPS-VGG-BiLSTM-Attn-Seed9998/best_accuracy.pth
```

라는 거만 뜨네요 ㅠㅠ

**Comment by BloomBerry** [comment]
안녕하세요. 저자님이 연구하신게 흥미로워 몇가지 문의사항을 남깁니다.

1. 본 연구는 Naver Clova Ai의 프로젝트를 기반으로 한 연구로, input image는 문장 전체를 둘러쌓는 bounding box를 기준으로 cropped된 이미지가 들어가는 것이 맞나요?
2. 마지막 분류에 사용한 class 갯수가 어떻게 될까요? (Alphanumeric =  알파벳 26 + 숫자 10 = 36 인걸로 아는데 한글은 어떻게 분류했는지가 궁금합니다)
3. Text-Detection과 Text-Recognition이 sequencial하게 수행한 연구결과가 있다면 공유 가능할까요?
감사합니다!
